### ISSUE TITLE
European Air Quality Data

### ISSUE THREAD

**Issue by pamvgomes** [skgrange/saqgetr#13]
Hello,

I'm writing to ask if you are aware that access to data from the most recent air quality stations only lasts until February 2024. Do you know what the problem is? Thanks.

Regards,

Paulo Gomes

**Comment by skgrange** [comment]
Hello,
The data that saqgetr accesses are no longer updated and the last update was conducted on February 17, 2024. I no longer have access to the servers that host these data and the API can now be considered retired (see the first note in the readme). For now, I will not pull the package from CRAN, but I may do in the future. Good luck in finding an alternative. 
Stuart.

**Comment by pamvgomes** [comment]
Thank you.

 

De: Stuart Grange ***@***.***> 
Enviada: 6 de agosto de 2024 07:18
Para: skgrange/saqgetr ***@***.***>
Cc: pamvgomes ***@***.***>; Author ***@***.***>
Assunto: Re: [skgrange/saqgetr] European Air Quality Data (Issue #13)

 

Hello,
The data that saqgetr accesses are no longer updated and the last update was conducted on February 17, 2024. I no longer have access to the servers that host these data and the API can now be considered retired (see the first note in the readme). For now, I will not pull the package from CRAN, but I may do in the future. Good luck in finding an alternative.
Stuart.

**Comment by skgrange** [comment]
No problems.
