### ISSUE TITLE
Data updated only by 12-06-2020 using get_saq_observations()

### ISSUE THREAD

**Issue by AdaCaoShiyu** [skgrange/saqgetr#2]
Hi Stuart,
I am doing an air pollution research, want to collect the UK hourly air pollutant data as recent as possible. However, when using **get_saq_observations()** as the example shows, it only updates till 12-June,2020 . 

I wonder can that data be updated till the end of June, or the early of July?

Yours Sincerely,
Ada

**Comment by skgrange** [comment]
Hello Ada. The re-databasing I do for this API is done about once a month. This could be done much more frequency, but I do not have full control on the network and servers which host the data files. Once a month I make an effort to update everything and copy the files. Luckily, this was on my list today and has been done. Therefore, the files will be mirrored to the public server and available from about 08:00 tomorrow (British local time). The European Commission's database is lagging a bit this month which happens quite a lot, so we have observations until July 2. Enjoy! Stuart.
