### ISSUE TITLE
get_saq_sites(): connection cannot be established

### ISSUE THREAD

**Issue by FinkLea** [skgrange/saqgetr#3]
Hello,

I'm running into the error:
**Error in open.connection(con, "rb") : HTTP error 403.**
when trying to import the sites information with **get_saq_sites()**.

This error occurs already since two weeks.
Maybe you can help me on this issue?

Thank you!
Greetings,
Lea

**Comment by skgrange** [comment]
Hello Lea,
You are correct, there is an issue with the remote server over the Christmas break. I am looking into things now and I will get back to you when things are resolved. Happy New Year and talk soon,
Stuart.

**Comment by FinkLea** [comment]
Thank you, Stuart!

**Comment by skgrange** [comment]
I have resolved the issue with the data files so **saqgetr** should work as expected again from now onwards. Enjoy, Stuart.
